const DRONE_COMMANDS_PORT = 8889;
const DRONE_STATUS_PORT = 8890;
const DRONE_HOST = '192.168.10.1';
const HEART_BEET_INTERVAL = 5000;
const SERVER_PORT = 3000;

exports.default = {
  DRONE_COMMANDS_PORT,
  DRONE_STATUS_PORT,
  DRONE_HOST,
  HEART_BEET_INTERVAL,
  SERVER_PORT,
}